# Generated by Django 2.2.4 on 2019-08-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizens',
            name='import_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_id', to='citizens.Imports'),
        ),
    ]
